name: Fetch latest notes sqlite db
on:
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch:

env:
  USER_EMAIL: ${{ secrets.USER_EMAIL }}
  USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  USER_USERNAME: ${{ secrets.USER_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup git
      run: |
        git config user.email "${USER_EMAIL}"
        git config user.name "${USER_USERNAME}"
        git remote set-url origin https://${USER_USERNAME}:${USER_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git checkout main
    
    - name: Fetch sqlite db
      run: make download-notes

    - name: Commit latest
      run: make commit-notes
